<?php

return [
  'name' => 'UnitConverter',
  'units' => [
    // ==================== Amount (Jumlah Zat) ====================
    ['class' => PhpUnitConversion\Unit\Amount\AttoMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\CentiMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\DecaMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\DeciMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\ExaMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\FemtoMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\GigaMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\HectoMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\KiloMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\MegaMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\MicroMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\MilliMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\Mole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\NanoMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\PetaMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\PicoMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\Quantity::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\TeraMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\YoctoMole::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Amount\YottaMole::class, 'system' => 'SI'],

    // ==================== Area ====================
    ['class' => PhpUnitConversion\Unit\Area\Acre::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Area\Are::class, 'system' => 'Metric'],
    ['class' => PhpUnitConversion\Unit\Area\Hectare::class, 'system' => 'Metric'],
    ['class' => PhpUnitConversion\Unit\Area\Perch::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Area\Rood::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Area\Section::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Area\SquareAttoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquareCentiMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquareDecaMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquareDeciMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquareExaMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquareFemtoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquareGigaMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquareHectoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquareInch::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Area\SquareInternationalYard::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Area\SquareKiloMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquareMegaMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquareMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquareMicroMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquareMilliMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquareNanoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquarePicoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquareYoctoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Area\SquareYottaMeter::class, 'system' => 'SI'],

    // ==================== Length ====================
    ['class' => PhpUnitConversion\Unit\Length\AttoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\Cable::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Length\CentiMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\Chain::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Length\DecaMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\DeciMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\ExaMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\Fathom::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Length\FemtoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\Foot::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Length\Furlong::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Length\GigaMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\HectoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\ImperialCable::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Length\ImperialFathom::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Length\ImperialNauticalMile::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Length\Inch::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Length\InternationalYard::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Length\KiloMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\League::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Length\MegaMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\Meter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\MicroMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\Mile::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Length\MilliMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\NanoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\NauticalMile::class, 'system' => 'Nautical'],
    ['class' => PhpUnitConversion\Unit\Length\PetaMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\PicoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\TeraMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\Yard::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Length\YoctoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Length\YottaMeter::class, 'system' => 'SI'],

    // ==================== Mass ====================
    ['class' => PhpUnitConversion\Unit\Mass\AttoGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\AvoirdupoisPound::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Mass\CentiGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\DecaGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\DeciGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\Drachm::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Mass\Dram::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Mass\ExaGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\FemtoGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\GigaGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\Grain::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Mass\Gram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\HectoGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\KiloGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\LongHundredWeight::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Mass\LongTon::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Mass\MegaGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\MicroGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\MilliGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\NanoGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\Ounce::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Mass\PennyWeight::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Mass\PetaGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\PicoGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\Quarter::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Mass\ShortHundredWeight::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Mass\ShortTon::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Mass\Stone::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Mass\TeraGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\TroyPound::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Mass\YoctoGram::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Mass\YottaGram::class, 'system' => 'SI'],

    // ==================== Temperature ====================
    ['class' => PhpUnitConversion\Unit\Temperature\Celsius::class, 'system' => 'Metric'],
    ['class' => PhpUnitConversion\Unit\Temperature\Fahrenheit::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Temperature\Kelvin::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Temperature\Rankine::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Temperature\Romer::class, 'system' => 'Other'],

    // ==================== Time ====================
    ['class' => PhpUnitConversion\Unit\Time\Day::class, 'system' => 'Other'],
    ['class' => PhpUnitConversion\Unit\Time\Hour::class, 'system' => 'Other'],
    ['class' => PhpUnitConversion\Unit\Time\JulianYear::class, 'system' => 'Other'],
    ['class' => PhpUnitConversion\Unit\Time\MicroSecond::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Time\MilliSecond::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Time\Minute::class, 'system' => 'Other'],
    ['class' => PhpUnitConversion\Unit\Time\NanoSecond::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Time\Second::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Time\Week::class, 'system' => 'Other'],
    ['class' => PhpUnitConversion\Unit\Time\Year::class, 'system' => 'Other'],

    // ==================== Velocity ====================
    ['class' => PhpUnitConversion\Unit\Velocity\FootPerHour::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Velocity\FootPerMinute::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Velocity\FootPerSecond::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Velocity\InchPerHour::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Velocity\InchPerMinute::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Velocity\InchPerSecond::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Velocity\KiloMeterPerHour::class, 'system' => 'Metric'],
    ['class' => PhpUnitConversion\Unit\Velocity\Knot::class, 'system' => 'Nautical'],
    ['class' => PhpUnitConversion\Unit\Velocity\MeterPerSecond::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Velocity\MilePerHour::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Velocity\MilePerMinute::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Velocity\MilePerSecond::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Velocity\MilesPerHour::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Velocity\MilesPerMinute::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Velocity\MilesPerSecond::class, 'system' => 'Imperial'],

    // ==================== Volume (lengkap) ====================
    // SI & metric prefixes
    ['class' => PhpUnitConversion\Unit\Volume\Liter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\DecaLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\HectoLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\KiloLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\MegaLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\GigaLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\TeraLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\PetaLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\ExaLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\DeciLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CentiLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\MilliLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\MicroLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\NanoLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\PicoLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\FemtoLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\AttoLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\ZeptoLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\YoctoLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\YottaLiter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\ZettaLiter::class, 'system' => 'SI'],

    // SI cubic meter & prefixes
    ['class' => PhpUnitConversion\Unit\Volume\CubicMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicDecaMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicHectoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicKiloMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicMegaMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicGigaMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicTeraMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicPetaMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicExaMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicDeciMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicCentiMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicMilliMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicMicroMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicNanoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicPicoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicFemtoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicAttoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicZeptoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicYoctoMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicYottaMeter::class, 'system' => 'SI'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicZettaMeter::class, 'system' => 'SI'],

    // Imperial liquid & dry
    ['class' => PhpUnitConversion\Unit\Volume\Gallon::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Volume\Quart::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Volume\Pint::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Volume\FluidOunce::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Volume\FluidDrachm::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Volume\FluidScruple::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Volume\Gill::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Volume\Minim::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Volume\Hogshead::class, 'system' => 'Imperial'],

    // US customary liquid
    ['class' => PhpUnitConversion\Unit\Volume\USLiquidGallon::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\USLiquidQuart::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\USLiquidPint::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\USCup::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\USFluidOunce::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\USFluidDram::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\USGill::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\USMinim::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\USShot::class, 'system' => 'US'],

    // US dry
    ['class' => PhpUnitConversion\Unit\Volume\DryGallon::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\DryQuart::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\DryPint::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\Bushel::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\Peck::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\DryBarrel::class, 'system' => 'US'],

    // Cooking & others
    ['class' => PhpUnitConversion\Unit\Volume\Tablespoon::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\Teaspoon::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\OilBarrel::class, 'system' => 'US'],
    ['class' => PhpUnitConversion\Unit\Volume\LiquidBarrel::class, 'system' => 'US'],

    // Imperial length-based
    ['class' => PhpUnitConversion\Unit\Volume\CubicFoot::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicInch::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Volume\CubicYard::class, 'system' => 'Imperial'],
    ['class' => PhpUnitConversion\Unit\Volume\AcreFoot::class, 'system' => 'Imperial'],
  ]
];